version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5009:5000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:admin@db:5432/postgres
      - JWT_SECRET_KEY=Farhan
      - REDIS_URL=redis://redis:6379/0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"

volumes:
  pgdata:
